title: Ghost CMS | Jekyll Themes Development – Anvod Studio.
logo:
description: Anvod Studio creates modern, minimal Ghost & Jekyll themes focused on the content, speed and simplicity.
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Anvod Studio

# Hero Settings
hero-title: Welcome to Anvod Studio
hero-subtitle: We create premium Ghost & Jekyll themes for creative people that appreciate quality and simplicity.
hero-img: /img/hero_bg.jpg

# Contact links
twitter: https://twitter.com/anvodstudio
github: https://github.com/anvodstudio
email: anvodstudio@gmail.com

# Google Analytics
google-analytics: # Add your identifier.

# Collestions
collections:
  posts:
    output: true
    permalink: /blog/:title
  
  ghost-themes:
    output: false

  jekyll-themes:
    output: false

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - sass
