# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Anvod Studio
description: Anvod Studio - A New View Of Design
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anvodstudio.com" # the base hostname & protocol for your site, e.g. http://example.com
email: anvodstudio@gmail.com
disqus: anvodstudio
twitter: https://twitter.com/anvodstudio
instagram: https://www.instagram.com/anvodstudio/
pinterest:
github: https://github.com/anvodstudio
themeforest:

# Hero
hero-title: Welcome to Anvod Studio
hero-tagline: We create premium custom websites for creative people and companies that appreciate quality and simplicity.

# Build settings
markdown: kramdown
paginate_path: "/page/:num"

include:
  - _pages

permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

#Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
